### ISSUE TITLE
aurelia-protractor has implicit any type

### ISSUE THREAD

**Issue by AdamWillden** [aurelia/typings#1]
@EisenbergEffect I tried enabling the `noImplicitAny` rule on the `typescript-aspnetcore` skeleton but my build fails because `waitForRouterComplete();` is an implicit any type as can be seen below. 

I'm not sure what the type should be. Can this be fixed?

It's the only issue I have, I have manually modified my typings file for now to make it an **explicit** any.

```ts
// Type definitions for Aurelia Protractor extensions
// Project: https://github.com/aurelia/skeleton-navigation
// Definitions by: Enrapt <https://github.com/Enrapt>, Kirill Grishin <https://github.com/KirillGrishin>

// Extend existing interfaces with additional functionality from Aurelia Protractor Extender (aurelia.protractor.js)

declare module protractor {
  interface IBrowser extends protractor.Protractor {
    loadAndWaitForAureliaPage(url: string): protractor.Protractor;
    waitForRouterComplete();
  }

  interface IProtractorLocatorStrategy {
    valueBind(bindTarget: string): webdriver.Locator;
  }
}
```

**Comment by EisenbergEffect** [comment]
Can you submit a PR to the aurelia-protractor repo? We can get a release out with the update.

**Comment by AdamWillden** [comment]
I'm not sure what the type should be or which repo needs updating. Can you point me in the right direction?

I've found [this](https://github.com/aurelia/protractor-plugin/blob/master/protractor.d.ts), but that already has types and doesn't quite match...

**Comment by EisenbergEffect** [comment]
The repo you linked above is the new protractor plugin d.ts. @niieani Can you comment on the differences?

**Comment by niieani** [comment]
The protractor typings from this repo are not used anymore. All the skeletons were updated to the protractor 4.0 which includes its own typings, and the aurelia extension is typed in the aurelia-protractor-plugin module and repository. We could probably remove those old typings from here, so we don't cause confusion. But the OP should upgrade to use aurelia-protractor-plugin.

**Comment by EisenbergEffect** [comment]
I'll remove the invalid typings...

**Comment by niieani** [comment]
@EisenbergEffect Note that older versions of the skeleton, which used the Typings module, might still include typings from here, so you could be breaking some of the older builds.

**Comment by EisenbergEffect** [comment]
Doh. Now I have to add them back.

**Comment by AdamWillden** [comment]
@niieani I only downloaded my skeleton (typescript-aspnetcore) recently in the last week or so. When was that change done? Is it possible that something was left over in the skeleton and still needs clearing up?

Does this line need removing? https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-typescript-aspnetcore/src/skeleton/typings.json#L30

**Comment by niieani** [comment]
Oh, the _aspnetcore_ skeletons... I'm not maintaining those since I don't have a Windows environment with VS setup. Somebody else should look at those, not sure if @AshleyGrant was maintaining them? If I understand right, those aspnetcore skeletons are just JSPM skeletons with a wrapper. Would a simple script be able keep both up-to-date with each other?
